version: "3.7"
services:
  app:
    build:
      context: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/myportfolio:cached
      - public-data:/myportfolio/public:cached
      - tmp-data:/myportfolio/tmp:cached
      - log-data:/myportfolio/log:cached
    depends_on:
      - db

  db:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: myportfolio_development
      MYSQL_ROOT_PASSWORD: Pierre51020
      MYSQL_USER: myportfolio
      MYSQL_PASSWORD: Pierre51020!
    volumes:
      - mysql_data:/var/lib/mysql:cached
    ports:
      - "3306:3306"

  test-db:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: myportfolio_test
      MYSQL_ROOT_PASSWORD: Pierre51020
      MYSQL_USER: myportfolio
      MYSQL_PASSWORD: Pierre51020!
    ports:
      - "3307:3306"
    cap_add:
      - SYS_NICE

  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/myportfolio/public:cached
      - tmp-data:/myportfolio/tmp:cached
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  mysql_data:
  public-data:
  tmp-data:
  log-data:
