version: "3"
services:
  app:
    build:
      context: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/myportfolio
      - public-data:/myportfolio/public
      - tmp-data:/myportfolio/tmp
      - log-data:/webapp/log
    depends_on:
      - db

  db:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: myportfolio_development
      MYSQL_ROOT_PASSWORD: Pierre51020
      MYSQL_USER: myportfolio
      MYSQL_PASSWORD: Pierre51020!
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  test-db:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: myportfolio_test
      MYSQL_ROOT_PASSWORD: Pierre51020
      MYSQL_USER: myportfolio
      MYSQL_PASSWORD: Pierre51020!
    ports:
      - "3307:3306"

  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/myportfolio/public
      - tmp-data:/myportfolio/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  mysql_data:
  public-data:
  tmp-data:
  log-data:
