# MySQL. Versions 5.5.8 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html
#

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: myportfolio_development
  pool: 5
  username: myportfolio
  password: Pierre51020!
  host: db

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: myportfolio_test
  pool: 5
  username: myportfolio
  password: Pierre51020!
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOSTNAME'] %>
