development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: myportfolio_development
  pool: 5
  username: myportfolio
  password: Pierre51020!
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: myportfolio_test
  pool: 5
  username: myportfolio
  password: Pierre51020!
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOSTNAME'] %>
